### ISSUE TITLE
Feature request: Make proxy_country accept a string or an iterable

### ISSUE THREAD

**Issue by pjmattingly** [ScrapingAnt/scrapingant-client-python#13]
It would be nice if the "proxy_country" parameter to general_request() would accept either a string or an iterable. This way a country for the proxy could be specified as one or more countries.

For example, current functionality is (roughly):

```
from scrapingant_client import ScrapingAntClient

# Define URL with a dynamic web content
url = "https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=engagement&btnG="

# Create a ScrapingAntClient instance
client = ScrapingAntClient(token=<token>)

# Get the HTML page rendered content
page_content = client.general_request(url, proxy_country='US').content
```

Then the proposed functionality might be:

```
from scrapingant_client import ScrapingAntClient

# Define URL with a dynamic web content
url = "https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=engagement&btnG="

# Create a ScrapingAntClient instance
client = ScrapingAntClient(token=<token>)

# Get the HTML page rendered content
page_content = client.general_request(url, proxy_country=['US', 'ES', 'IT']).content
```

The order of preference of proxy's in each country would be implicitly assumed by the ordering of the strings indicating countries.

**Comment by kami4ka** [comment]
@pjmattingly Hey!
Thanks for the request.
What is the expected behavior? Should the proxy country be randomly picked from the iterable?

**Comment by pjmattingly** [comment]
Sure, a greedy algorithm seems reasonable. The order indicates preference,
but whichever is available first would be a valid choice.

**Comment by kami4ka** [comment]
Yep, but all the proxy countries are available, so you can just iterate over the array and place a needed one while iteration. Or, perhaps, I miss the idea :-)

Can you please add a use case for it? What would you like to achieve by this behavior?

**Comment by pjmattingly** [comment]
Sure.

My use-case is related to the governments of some of the countries where the proxies reside. I wouldn't mind proxying through the US, Italy, or Spain (as in the example), but I have concerns about proxying through China.

A first concern is political repression. China is famous for their "Great Firewall" and cracking down on "undesirables" through their internet usage. Having my traffic pass through their portion of the Internet seems to present possible complications of this type. I reside in relatively wealthy western nation, but not all of my potential users might. Thus, their internet traffic as potentially capturable through Chinese proxies may have unintended negative consequences for them.

A second concern is a moral argument. China is famous for using slave labor and committing genocide, I'd rather avoid being associated with that. While I acknowledge that there appears to be a rather large leap to associate proxying with being associated with China's policies, I would prefer to avoid interacting with them when at all possible. In addition, some of the users of my application may feel similarly and wish to avoid using anything Chinese. My application is primarily targeted at Scientists and Researchers.

**Comment by kami4ka** [comment]
@pjmattingly thanks for the details.

@megabotan can you please advise with an example snippet for this case? I guess this feature might be implemented without an actual change of the client code. What do you think?

**Comment by megabotan** [comment]
@pjmattingly great story! Thanks for sharing your use case.
As far as I understand, you want to randomly proxy your request through one of the countries on the list.
Here is the snippet of how you can achieve this.

```python3
import random

from scrapingant_client import ScrapingAntClient

url = "https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=engagement&btnG="

client = ScrapingAntClient(token=<token>)

page_content = client.general_request(url, proxy_country=random.choice(['US', 'ES', 'IT'])).content
```

I hope this helps.

**Comment by pjmattingly** [comment]
Hi Andrew,

That looks good, but I have a concern. As I understand the proxies rotate
from time to time. It's possible that a proxy from a country in the list
might not be available and chosen by choice(). There doesn't seem to be any
functionality to fall back to another in the list if a proxy can't be used.

I suppose we could make a loop to wait for proxy to be chosen and return
content. Then, is there a way to get the countries that are available for
proxying through at any given time? I suppose we could scrape your proxy
page for that, if nothing else. XD

Otherwise, I think on github there's a list of all possible countries that
are supported for proxying, and that list could be used.

Thanks Andrew, I think this resolves my request.

Cheers.

--P

**Comment by megabotan** [comment]
Hi, @pjmattingly.

This repository is just a handy wrapper of our [Web Scraping API](https://scrapingant.com).
Our proxy pool has over 40.000 high-quality proxies, which are always available, so you no need to be worried about proxy accessibility. Our service automatically rotates proxies; on each request, a random proxy is used.

 If you specify a country, a random proxy from this country is used to process the request.  

We are not using proxies from the Free Proxy page.

**Comment by pjmattingly** [comment]
Okay, great! Thanks for the clarification.
