### ISSUE TITLE
scraping client doesn't work with some urls that contain query parameters.

### ISSUE THREAD

**Issue by tombohub** [ScrapingAnt/scrapingant-client-python#25]
I have this url example : 

`https://www.comecompany.com/apim/items/price?id=599745&number=2413`

In order to work url needs to be encoded. When I create scraping api GET request by hand it works. I get json response with data I need.

Using scraping ant client I have 2 options: 

1. using url as it is:

`result = scraping_ant_client.general_request(url=url)` - this gives me missing subscription key error from the api server i am trying to scrape.

2. trying to encode the url:

```python 
from urllib.parse import quote 
result = scraping_ant_client.general_request(url=quote(url))
``` 

this gets me an error: `scrapingant_client.errors.ScrapingantInvalidInputException: {"detail":"Wrong host part of url. Please check out the documentation: https://docs.scrapingant.com/"}`

you are using POST request in your client

**Comment by kami4ka** [comment]
@tombohub the lib already encodes everything for you (URL, JS snippet, etc.), so no need to use `quote`

Also, for now both GET and POST requests to our API do the same - getting data from a webpage (GET request).
We've used POST for a simpler data flow between the client and API, but they both doing the same.

**Comment by tombohub** [comment]
I don't know what to say. I just hand coded POST and GET request. For this particular link GET works, POST doesn't.

I can give you link privately and you can do tests.

**Comment by kami4ka** [comment]
@tombohub are you trying to make a POST request to some URL using ScrapingAnt API?

**Comment by tombohub** [comment]
@kami4ka I am making POST version of request to scraping ant api. 

```
curl --request POST \
--url 'https://api.scrapingant.com/v1/general' \
--header 'x-api-key: <YOUR-API-KEY>' \
--header 'accept: application/json' \
--header 'content-type: application/json' \
--data '{ "url": "https://example.com"}'
```

```python
url = 'https://api.scrapingant.com/v1/general'
        headers = {
            'x-api-key': "API-KEY",
            'content-type': "application/json",
            'accept': "application/json"
            }
        payload = "{ \"url\": \"https://somecompany.com/api?item=4333", \"browser\": false, \"return_text\": true}"
        response = requests.post(url, data=payload, headers=headers)
```

**Comment by kami4ka** [comment]
@tombohub could you, please, send us the website URL you're trying to scrape at support@scrapingant.com, so we can debug it?

**Comment by tombohub** [comment]
@kami4ka of course, sending right now

**Comment by kami4ka** [comment]
Closing the issue as it is not related to the library.
