### ISSUE TITLE
How to control request method GET or POST like curl -X "POST" "url" ?

### ISSUE THREAD

**Issue by cimuxy** [ScrapingAnt/scrapingant-client-python#30]

**Comment by megabotan** [comment]
Hi. We have added post requests in our API's new (v2) version. Currently, the Python client works with API v1. 
I'll make the changes needed in the next few days. Thanks for the report!

**Comment by megabotan** [comment]
I just released version 2.0.0 of the client.
Here is an example of how to make a POST request:
https://github.com/ScrapingAnt/scrapingant-client-python/tree/2.0.0#sending-post-request
